### PR TITLE
trivial

### PR DESCRIPTION
**Pull request by tpolecat**

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
LGTM 😄

**Comment by tpolecat** [comment]
Heroku is deploying a test version of the app based on the PR. It should show up here in a minute.

**Comment by tpolecat** [comment]
This is awesome. Click "view deployment" above and it will open the test version of the app.

**Comment by cquiroz** [comment]
Nice, did it deploy before merging?

**Comment by tpolecat** [comment]
Yes, it creates the test app so you can play with it before merging. After merging it deletes the app and redeploys the main app from master.

**Comment by tpolecat** [comment]
Really the main app linked to `master` should be the staging app, and then there's a button you can click to promote staging to production. If you look in Heroku (and you're logged in and have joined the team) you can see it. https://dashboard.heroku.com/pipelines/ceeeb4ed-f993-4655-8581-6db76c75b328

**Comment by cquiroz** [comment]
Very nice. How do you handle db migrations?

**Comment by tpolecat** [comment]
> How do you handle db migrations?

I don't know yet.

**Comment by tpolecat** [comment]
Ok so it redeployed when I pushed new code, and I turned on Heroku CI so it's running tests now too.

**Comment by tpolecat** [comment]
An important thing to note here is that our workflow has to change a bit. Instead of having your own fork you must clone THIS repository and work on branches that you push here. `master` is protected so you can't accidentally push to it or delete it, which I believe was our original concern.

**Comment by tpolecat** [comment]
Ok now when I merge it should re-deploy the main app.

**Comment by swalker2m** [comment]
Hmm, when I click "View deployment" it just says

> There's nothing here, yet.

**Comment by tpolecat** [comment]
That's because I merged the PR. When you do that it destroys the review instance.

**Pull request merged**
